# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zipcode',
            field=models.CharField(default='222000', max_length=200),
        ),
    ]
